kit/issues/urls.py
from django.conf.urls.defaults import patterns, url
from views import *

urlpatterns = patterns('',
    url(r'list/$', IssueListView.as_view(), name='issues_list'),
    url(r'report/$', IssueReportsView.as_view(), name='issues_report'),
    url(r'view/(?P<pk>\d+)/$', IssueDetailView.as_view(), name='issues_view'),
    url(r'edit/(?P<pk>\d+)/$', IssueEdit.as_view(), name='issues_edit'),
    url(r'new/$', IssueCreate.as_view(), name='issues_new'),
    url(r'prefs/$', Preferences.as_view(), name='preferences'),

    url(r'toggle-subscribe/(?P<pk>\d+)/$', ToggleSubscribe.as_view(), name='toggle_subscribe'),
    url(r'comment/$', CommentCreate.as_view(), name='comment_new'),
)

kit/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

from kit.issues.views import HomePage, ManageProject, PUCreate, PUUpdate

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kit.views.home', name='home'),
    # url(r'^kit/', include('kit.foo.urls')),

    url(r'^$', HomePage.as_view(), name='projects_list'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/login/', 'django.contrib.auth.views.login'),
    url(r'^user/logout/', 'django.contrib.auth.views.logout', dict(next_page='/')),

    # these would break the previous regs
    url(r'^(?P<project>.+)/issues/', include('kit.issues.urls')),
    url(r'^(?P<project>.+)/activity/', include('kit.activity.urls')),
    url(r'^(?P<project>.+)/manage/$', ManageProject.as_view(), name='project_manage'),
    url(r'^(?P<project>.+)/manage/add/$', PUCreate.as_view(), name='project_manage_add'),
    url(r'^(?P<project>.+)/manage/edit/(?P<pk>\d+)/$', PUUpdate.as_view(), name='project_manage_edit'),


)

kit/issues/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings

class ProjectUser(models.Model):
    ROLES = (('a', 'admin'), ('d', 'developer'), ('r', 'reporter'))
    user = models.ForeignKey(User)
    project = models.ForeignKey('Project')
    role = models.CharField(max_length=1, choices=ROLES, default='r')

    class Meta:
        unique_together = ('user', 'project')

    @classmethod
    def can_read(cls, user, project):
        try:
            exists = ProjectUser.objects.get(project=project, user=user)
            return True
        except:
            return user.is_superuser

    @classmethod
    def get_role(cls, user, project):
        try:
            exists = ProjectUser.objects.get(project=project, user=user)
            return exists.get_role_display()
        except:
            if user.is_superuser:
                return 'admin'
            return ''

    def get_absolute_url(self):
        return '/%s/manage/' % self.project.name

    def __unicode__(self):
        return self.user.__unicode__() + '-' + self.project.__unicode__()

class Project(models.Model):
    name = models.CharField(max_length=64, unique=True)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    public = models.BooleanField(default=False, blank=True)

    users = models.ManyToManyField(User, through=ProjectUser, blank=True)

    @property
    def stats(project):
        class Stat:
            def __getitem__(self, item):
                if item == 'open':
                    return project.issue_set.filter(active=True).count()
                if item == 'new':
                    return project.issue_set.filter(status='n').count()
                if item == 'all':
                    return project.issue_set.all().count()
                if item == 'closed':
                    return project.issue_set.filter(active=False).count()
        return Stat()

    def get_created_subscribers(self):
        """ Return a list of project users subscribed to "Issue created" notifications
        """
        exclude = [up.user.id for up in UserPreference.objects.filter(project=self, name='subscribe_created', value='False')]
        users = self.users.exclude(id__in=exclude)
        return users

    def __unicode__(self):
        return self.name

class Tracker(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=64)
    project = models.ForeignKey(Project, blank=True, default=None, null=True)

    def __unicode__(self):
        return self.name

class Issue(models.Model):
    STATUSES = (('n', 'New'), ('c', 'Confirmed'), ('p', 'In progress'), ('r', 'Resolved'),
                ('f', 'Fixed'), ('i', 'Invalid'), ('w', "Won't fix"))
    PRIORITIES = ((10, 'Low'), (20, 'Medium'), (50, 'Normal'), (70, 'High'), (100, 'Critical'))

    tracker = models.ForeignKey(Tracker)
    status = models.CharField(max_length=1, choices=STATUSES, default='n', blank=True)
    reporter = models.ForeignKey(User, related_name='reporter')
    assigned = models.ForeignKey(User, related_name='assigned', default=None, blank=True, null=True)
    priority = models.IntegerField(default=50, blank=True, choices=PRIORITIES) # 0 to 100
    category = models.ForeignKey(Category, blank=True, null=True, default=None)
    project = models.ForeignKey(Project)
    title = models.CharField(max_length=200)
    text = models.TextField(max_length=1500, blank=True, default='')
    active = models.BooleanField(default=True, blank=True, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    dependencies = models.ManyToManyField('Issue', related_name='block', blank=True)
    subscribers = models.ManyToManyField(User, related_name='subscribed', blank=True)

    def get_priority_display(self):
        if self.priority < 20:
            return 'Low'
        elif self.priority < 50:
            return 'Normal'
        elif self.priority < 80:
            return 'Important'
        else:
            return 'Critical'

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('issues_view', args=(self.project.name, self.id))

    @property
    def comments(self):
        return self.comment_set.filter(reply_to=None).order_by('date')

    def save(self):
        is_new = (self.id is None)
        was_active = self.active
        if self.status in ('f', 'i', 'w'):
            self.active = False
            if was_active:
                if not self.assigned:
                    self.assigned = self.reporter
        else:
            self.active = True
        # pre save
        if is_new:
            super(Issue, self).save()
            self.subscribers.add(self.reporter)
            if self.assigned:
                self.subscribers.add(self.assigned)
        else:
            # assigned to
            had_assigned = Issue.objects.get(id=self.id).assigned
            if (had_assigned != self.assigned) and self.assigned:
                self.subscribers.add(self.assigned)

        super(Issue, self).save()
        
    def get_changes(self, initial, extra=None, excludes=[]):
        changes = {}
        def get_obj_val(cls, id):
            try:
                return unicode(cls.objects.get(pk=id))
            except:
                return 'None'

        for field in self._meta.fields:
            if not (field.name in excludes):
                current_value, initial_value = field.value_from_object(self), field.value_from_object(initial)
                if current_value != initial_value:
                    changes[field.verbose_name] = (current_value, initial_value)

                    if field.flatchoices:
                        value, zero = changes[field.verbose_name]
                        value = dict(field.flatchoices).get(value, value)
                        changes[field.verbose_name] = (value, zero)
                    elif field.name in ('assigned', 'reporter'):
                        changes[field.verbose_name] = (get_obj_val(User, current_value),
                           get_obj_val(User, initial_value))
                    elif field.name == 'tracker':
                        changes[field.verbose_name] = (get_obj_val(Tracker, current_value),
                            initial_value)
                    elif field.name == 'category':
                        changes[field.verbose_name] = (get_obj_val(Category, current_value),
                            initial_value)
        if extra:
            for k, v in extra.iteritems():
                if set(getattr(initial, k).all()) != set(v):
                    changes[k] = (','.join([str(a) for a in v]), '')
        return changes

    def __unicode__(self):
        return u"#%d %s" % (self.id, self.title)

    def subscribers_display(self):
        return ','.join(map(unicode, self.subscribers.all()))

    def toggle_subscribe(self, user):
        if user in self.subscribers.all():
            self.subscribers.remove(user)
        else:
            self.subscribers.add(user)

    def get_email_subscribers(self):
        exclude = [up.user.id for up in UserPreference.objects.filter(project=self.project, name='subscribe_updated', value='False')]
        return self.subscribers.exclude(id__in=exclude)

class Comment(models.Model):
    issue = models.ForeignKey(Issue)
    reply_to = models.ForeignKey('Comment', related_name='reply', null=True, blank=True, default=None)
    author = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=2000)

    @property
    def children(self):
        return self.reply.all().order_by('date')

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('issues_view', args=(self.issue.project.name, self.issue.id))

    @classmethod
    def changed(cls, user, issue, changes=None, text=''):
        if changes:
            msg = 'Changed: \n\n'
            for k,v in changes.iteritems():
                msg += ' * **%s**: %s \n' % (k, v[0])
        else:
            msg = text

        newcomm = cls.objects.create(issue=issue, author=user, text=msg)
        cls.alert(issue, user, msg)

    @classmethod
    def alert(cls, issue, user, text, new=False):
        subject = '[%s] %s %s #%d %s' % (issue.project, user, 'changed' if not new else 'created', issue.id, issue.title)
        mail_from = '@'.join((settings.EMAIL_HOST_USER, settings.EMAIL_HOST))
        if new:
            mail_to = [u.email for u in issue.project.get_created_subscribers()]
        else:
            mail_to = [u.email for u in issue.get_email_subscribers()]
        mail_to = list(set(mail_to))
        text += '\n\n'+ settings.KIT_URL + issue.get_absolute_url()
        send_mail(subject, text, mail_from, mail_to, fail_silently=True)

    def __unicode__(self):
        return u"#%d %s: %s" % (self.issue.id, self.author, self.text[:50])


class UserPreference(models.Model):
    TYPES = (('s', 'str'),('b', 'boolean'))
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project, null=True, blank=True)
    name = models.CharField(max_length=128)
    value = models.CharField(max_length=256)

    type = models.CharField(max_length=1, choices=TYPES, default='b', blank=True)

    def get_value(self):
        if self.type == 'b':
            return self.value == 'True'
        return self.value

    def set_value(self, value):
        if self.type == 'b':
            self.value = 'True' if value else 'False'
        else:
            self.value = value
        self.save()

kit/resources/templates/issues/comment.html
{% load markup %}
{% load comments %}
<div class="comment">
    <img class="avatar avatar-min" src="{% gravatar c.author %}" />

    <div class="comment-head"><strong>{{ c.author }}</strong> on <span class="date">{{ c.date }}</span></div>
    <div class="comment-body">
        {% autoescape off %}
        <p>{{ c.text|markdown|linkify:project.name }}</p>
        {% endautoescape %}
        <div class="replies">
        {% for rc in c.children %}
            {% do_comment rc %}
        {% endfor %}
        </div>
    </div>
</div>
<div class="comment-spacer"></div>

kit/resources/templates/issues/comment_form.html
{% block content %}
{% if not user.is_authenticated %}
    Please <a href="{% url django.contrib.auth.views.login %}">login</a>
{% else %}
<form method="post" action="{% url comment_new project %}">
    <table>
        <tr><td colspan="2"></td>
            <td rowspan="2" valign="top">
            <button type="submit">Submit</button></td>
        </tr>
    {{ form.as_table }}
    <input type="hidden" name="author" value="{{ user.id }}" />
    </table>
    {% csrf_token %}
</form>
{% endif %}
{% endblock %}

kit/resources/templates/issues/issue_detail.html
{% extends 'issues/issue_list.html' %}
{% load markup %}
{% load comments %}
{% load issues %}

{% block sidebar %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <h2>{{ object.tracker }} #{{ object.pk }}</h2>
    <div class="issue">
    <h3>{{ object.title }}</h3>

    <table class="description"><tr>
     <td valign="top" width="30%">
        <p><strong>Status:</strong> {{ object.get_status_display }}</p>
        <p><strong>Priority:</strong> <span class="pri-{{ object.get_priority_display|lower }}">{{ object.get_priority_display }}</span></p>
        <p><strong>Assigned to:</strong> {{ object.assigned }}</p>
    </td>
    <td valign="top" width="30%">
    <p><strong>Reported by:</strong> {{ object.reporter }}</p>
    <p><strong>Category:</strong> {{ object.category }}</p>
    <p><strong>Last updated:</strong> {{ object.date_updated }}</p>
    </td>
    <td valign="top" width="30%">
        <p><strong>Depends:</strong>
        {% for i in object.dependencies.all %}
            {% issue i %}
        {% endfor %}
        </p>
        <p><strong>Blocks:</strong>
        {% for i in object.block.all %}
            {% issue i %}
        {% endfor %}
        </p>
        <p><strong>Subscribers</strong>
        <!--email:
            {% for i in object.get_email_subscribers %}
            {{ i }}
        {% endfor %}
        all:-->
        {% for i in object.subscribers.all %}
            {{ i }}
        {% endfor %}
        <a href="{% url toggle_subscribe project object.id %}">
        {% if is_subscribed %}
        Unsubscribe
        {% else %}
        Subscribe
        {% endif %}
        </a>
        </p>
    </td>
    </tr></table>

    <p><strong>Description</strong></p>
    {% autoescape off %}
        <p>{{ object.text|markdown|linkify:project.name }}</p>
    {% endautoescape %}
    </div>

    <div class="actions">
        {% if user.is_authenticated %}
        <a href="{% url issues_edit project object.id %}" onclick="show_form(); return false;">Modify</a>
        {% endif %}
    </div>

    <div class="hidden" id="modify-form">
        <p>
            <strong>Update</strong> <a href="#" onclick="toggle_more(); return false;">more</a>
        </p>

        <form action="{% url issues_edit project object.id %}" method="post">
            <div class="hidden" id="modify-more">
                <table>
                    <tr>
                        <td width="15%"><label for="id_tracker">Tracker:</label></td>
                        <td>{{ modifyform.tracker}}</td>
                    </tr>
                    <tr>
                        <td><label for="id_reporter">Reporter:</label></td>
                        <td>{{ modifyform.reporter}}</td>
                    </tr>
                    <tr>
                        <td><label for="id_title">Title:</label></td>
                        <td>{{ modifyform.title}}</td>
                    </tr>
                    <tr>
                        <td valign="top"><label for="id_text">Text:</label></td>
                        <td>{{ modifyform.text}}</td>
                    </tr>
                </table>
                <div class="hidden">
                    {{ modifyform.project }}
                </div>
            </div>
            <table>
                <tr>
                    <td width="15%"><label for="id_status">Status:</label></td>
                    <td width="35%">{{ modifyform.status }}</td>

                    <td><label for="id_dependencies">Depends:</label></td>
                    <td rowspan="4">{{ modifyform.dependencies }}</td>
                </tr>
                <tr>
                    <td><label for="id_assigned">Assigned:</label></td>
                    <td>{{ modifyform.assigned}}</td>
                </tr>
                <tr>
                    <td><label for="id_priority">Priority:</label></td>
                    <td>{{ modifyform.priority }}</td>
                </tr>
                <tr>
                    <td valign="top"><label for="id_category">Category:</label></td>
                    <td valign="top">{{ modifyform.category }}</td>
                </tr>
            </table>
            <div class="actions">
                <button type="submit">Save</button>
            </div>
            {% csrf_token %}
        </form>
    </div>

    <div class="comments">
    {% for c in object.comments %}
        {% do_comment c %}
    {% endfor %}
    </div>

    <div class="new-comment" id="new-comment">
        <h4>New comment</h4>
        {% include 'issues/comment_form.html' with form=commentform %}
    </div>
{% endblock %}

kit/resources/templates/issues/issue_form.html
{% extends 'issues/issue_list.html' %}

{% block content %}
<h2>{% if object %}Modify {{ object }}{% else %}New issue{% endif %}</h2>
<form method="post">
    <table>
    {{ form.as_table}}
    </table>
    <button type="submit">Save</button>

    <a href="{% if object %}{{ object.get_absolute_url }}{% else %}{% url issues_list project.name %}{% endif %}">Cancel</a>
    {% csrf_token %}
    {% if object %}
    {% else %}
    <input type="hidden" name="project" value="{{ project.id }}" />
    <input type="hidden" name="reporter" value="{{ user.id }}" />
    {% endif %}
</form>
{% endblock %}

kit/resources/templates/issues/issue_list.html
{% extends 'base.html' %}

{% block sidebar %}
    <h4>Issues</h4>
    <ul>
        <li><a href="{% url issues_list project %}">View all</a></li>
        <li><a href="{% url issues_report project %}">Report</a></li>
    </ul>

    <h4>Statistics</h4>
    <ul>
        <li>Open: {{ project.stats.open }}</li>
        <li>Closed: {{ project.stats.closed }}</li>
        <li>New: {{ project.stats.new }}</li>
    </ul>
{% endblock %}

{% block content %}
    <h2>Issues</h2>

    <fieldset><legend onclick="$('#filters-content').toggle();" style="cursor: hand;">Filters</legend>
    <div id="filters-content">
    <form action="" method="get" name="form">
        <table>
            <tr>
                <td>Status:</td>
                <td><select name="status">
                    <option value=""    {% if not status %}selected{% endif %}>any</option>
                    <option value="open"    {% if status == 'open' %}selected{% endif %}>open</option>
                    <option value="closed"  {% if status == 'closed' %}selected{% endif %}>closed</option>
                    {% for s in statuses %}
                    <option value="{{ s.0 }}" {% if status == s.0 %}selected{% endif %}>{{ s.1 }}</option>
                    {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>Category:</td>
                <td><select name="category">
                    <option value=""    {% if not category %}selected{% endif %}>any</option>
                    <option value="0"    {% if category == 0 %}selected{% endif %}>none</option>
                    {% for c in categories %}
                    <option value="{{ c.id }}" {% if category == c.id %}selected{% endif %}>{{ c }}</option>
                    {% endfor %}
                    </select>
                </td>
            </tr>
        </table>
        <div class="actions">
            <a href="#" onclick="form.submit();return false">Apply</a>
        </div>
    </form>
    </div>
    </fieldset>

    <table>
    <tr>
        <th>#</th>
        <th>Tracker</th>
        <th>Status</th>
        <th>Priority</th>
        <th>Subject</th>
        <th>Assigned</th>
        <th>Category</th>
        <th>Updated</th>
    </tr>

    {% for issue in object_list %}
    <tr>
        <td>{{ issue.pk }}</td>
        <td>{{ issue.tracker }}</td>
        <td>{{ issue.get_status_display }}</td>
        <td class="pri-{{ issue.get_priority_display|lower }}">{{ issue.get_priority_display }}</td>
        <td><a href="{% url issues_view issue.project issue.pk %}">{{ issue.title }}</a></td>
        <td align="center">{% if issue.assigned %}{{ issue.assigned }}{% else %}-{% endif %}</td>
        <td>{% if issue.category %}{{ issue.category }}{% else %}-{% endif %}</td>
        <td>{{ issue.date_updated }}</td>
    </tr>
    {% endfor %}
    </table>

{% endblock %}

kit/resources/templates/issues/preferences.html
{% extends 'base.html' %}

{% block content %}
    <h2>Preferences in {{ project }}</h2>

    <form method="post">
        <p>Email notifications:</p>
        <table>
            {{ prefsform.as_table }}
        </table>
        <button type="submit">Save</button>
        {% csrf_token %}
    </form>
{% endblock %}

kit/resources/templates/issues/project_manage.html
{% extends 'base.html' %}

{% block content %}
    <h2>Manage {{ project }}</h2>

    <h3>Users</h3>
    <table>
    {% for u in project.projectuser_set.all %}
        <tr>
            <td>{{ u.user }}</td>
            <td>{{ u.get_role_display }}</td>
            <td><a href="{% url project_manage_edit project u.id %}">Edit</a></td>
        </tr>
    {% endfor %}
    </table>

    <h4>Add user to project</h4>
    <form method="post" action="{% url project_manage_add project %}">
        <table>
        {{ puform.as_table }}
        </table>
        <button type="submit">Add</button>
        {% csrf_token %}
    </form>
    
    <h3>Categories</h3>
    <table>
    {% for c in project.category_set.all %}
        <tr>
            <td>{{ c }}</td>
            <td>{{ c.issue_set.count }}</td>
            <td>
                <a href="{% url admin:issues_category_change c.id %}">Edit</a>
            </td>
        </tr>
    {% endfor %}
    </table>
    <h4>Add category:</h4>
    <form method="post">
        <input type="text" name="name" size="20" />
        <input type="hidden" name="project" value="{{ project.id }}" />
        <button type="submit">Add</button>
        {% csrf_token %}
    </form>
{% endblock %}

kit/resources/templates/issues/projects.html
{% extends 'base.html' %}
{% load markup %}
{% load comments %}

{% block content %}
<h2>Select project</h2>

{% for project in projects %}
    <h3><a href="{% url issues_list project.name %}">{{ project.title }}</a></h3>
    {% autoescape off %}
    <p>{{ project.description|markdown|linkify }}</p>
    {% endautoescape %}
{% empty %}
    <p>No projects defined.</p>
{% endfor %}

{% endblock %}

kit/resources/templates/issues/projectuser_form.html
{% block content %}
{% if not user.is_authenticated %}
    Please <a href="{% url django.contrib.auth.views.login %}">login</a>
{% else %}
<form method="post" action="{% if object %}{% url project_manage_edit project object.id %}{% else %}{% url project_manage_add project %}{% endif %}">
    <table>
        <tr><td colspan="2"></td>
            <td rowspan="2" valign="top">
            <button type="submit">Submit</button></td>
        </tr>
    {{ form.as_table }}
    <input type="hidden" name="author" value="{{ user.id }}" />
    </table>
    {% csrf_token %}
</form>
{% endif %}
{% endblock %}

kit/resources/templates/issues/reports.html
{% extends 'issues/issue_list.html' %}

{% block content %}
    <h2>Report</h2>
    <h3>Tracker</h3>
    <table>
        <tr>
            <th></th>
            <th>all</th>
        </tr>
        {% for t in trackers %}
        <tr>
            <td>{{ t.name }}</td>
            <td align=center>{{ t.issue_set.all.count }}</td>
        </tr>
        {% endfor %}
    </table>

    <h3>Users</h3>
    <table>
        <tr>
            <th></th>
            <th>reported</th>
            <th>assigned</th>
            <th>closed</th>
        </tr>
        {% for u in users %}
        <tr>
            <td>{{ u }}</td>
            <td align=center>{{ u.stats.reported }}</td>
            <td align=center>{{ u.stats.assigned }}</td>
            <td align=center>{{ u.stats.closed }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}